# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:36:55+00:00

from __future__ import annotations

from enum import Enum
from typing import Union

from pydantic import BaseModel, Field, RootModel


class ErrorInvalidId(BaseModel):
    detail: str = Field(
        ...,
        description='Additional information about the error',
        examples=["ID '0A000000B0C9A1234' could not be found (type=MT)"],
    )
    instance: str = Field(
        ...,
        description='Internal Trace ID',
        examples=['bf0ca0bf927b3b52e3cb03217e1a1ddf'],
    )
    title: str = Field(
        ..., description='Generic error message', examples=['Invalid ID']
    )
    type: str = Field(
        ...,
        description='Link to error / remediation options',
        examples=['https://developer.nexmo.com/api-errors#invalid-id'],
    )


class ErrorInvalidJson(BaseModel):
    detail: str = Field(
        ...,
        description='Additional information about the error',
        examples=[
            'Unexpected character (\'"\' (code 34)): was expecting comma to separate Object entries'
        ],
    )
    instance: str = Field(
        ...,
        description='Internal Trace ID',
        examples=['bf0ca0bf927b3b52e3cb03217e1a1ddf'],
    )
    title: str = Field(
        ..., description='Generic error message', examples=['Invalid JSON']
    )
    type: str = Field(
        ...,
        description='Link to error / remediation options',
        examples=['https://developer.nexmo.com/api-errors#invalid-json'],
    )


class ErrorPrematureRedaction(BaseModel):
    detail: str = Field(
        ...,
        description='Additional information about the error',
        examples=["You must wait 60 minutes before redacting ID '0A000000B0C9A1234'"],
    )
    instance: str = Field(
        ...,
        description='Internal Trace ID',
        examples=['bf0ca0bf927b3b52e3cb03217e1a1ddf'],
    )
    title: str = Field(
        ..., description='Generic error message', examples=['Premature Redaction']
    )
    type: str = Field(
        ...,
        description='Link to error / remediation options',
        examples=['https://developer.nexmo.com/api-errors/redact#premature-redaction'],
    )


class ErrorThrottled(BaseModel):
    detail: str = Field(
        ...,
        description='Additional information about the error',
        examples=['Please wait, then retry your request'],
    )
    instance: str = Field(
        ...,
        description='Internal Trace ID',
        examples=['bf0ca0bf927b3b52e3cb03217e1a1ddf'],
    )
    title: str = Field(
        ..., description='Generic error message', examples=['Rate Limit Hit']
    )
    type: str = Field(
        ...,
        description='Link to error / remediation options',
        examples=['https://developer.nexmo.com/api-errors/redact#rate-limit'],
    )


class ErrorUnauthorized(BaseModel):
    error_title: str = Field(..., description='Error title', examples=['Unauthorized'])
    type: str = Field(
        ..., description='Machine readable error type', examples=['UNAUTHORIZED']
    )


class ErrorUnprovisioned(BaseModel):
    detail: str = Field(
        ...,
        description='Additional information about the error',
        examples=['User=ABC123 is not provisioned to redact product=SMS'],
    )
    instance: str = Field(
        ...,
        description='Internal Trace ID',
        examples=['bf0ca0bf927b3b52e3cb03217e1a1ddf'],
    )
    title: str = Field(
        ..., description='Generic error message', examples=['Authorisation error']
    )
    type: str = Field(
        ...,
        description='Link to error / remediation options',
        examples=['https://developer.nexmo.com/api-errors#unprovisioned'],
    )


class ErrorUnsupportedProduct(BaseModel):
    detail: str = Field(
        ...,
        description='Additional information about the error',
        examples=['No product corresponding to supplied string sms2!'],
    )
    instance: str = Field(
        ...,
        description='Internal Trace ID',
        examples=['bf0ca0bf927b3b52e3cb03217e1a1ddf'],
    )
    title: str = Field(
        ..., description='Generic error message', examples=['Invalid Product']
    )
    type: str = Field(
        ...,
        description='Link to error / remediation options',
        examples=['https://developer.nexmo.com/api-errors/redact#invalid-product'],
    )


class Product(Enum):
    sms = 'sms'
    voice = 'voice'
    number_insight = 'number-insight'
    verify = 'verify'
    verify_sdk = 'verify-sdk'
    messages = 'messages'


class Type(Enum):
    inbound = 'inbound'
    outbound = 'outbound'


class RedactTransaction(BaseModel):
    id: str = Field(
        ...,
        description='The transaction ID to redact',
        examples=['209ab3c7536542b91e8b5aef032f6861'],
    )
    product: Product = Field(
        ...,
        description='Product name that the ID provided relates to',
        examples=['sms'],
    )
    type: Type = Field(
        ..., description='Required if redacting SMS data', examples=['outbound']
    )


class TransactionPostResponse(
    RootModel[Union[ErrorPrematureRedaction, ErrorUnprovisioned]]
):
    root: Union[ErrorPrematureRedaction, ErrorUnprovisioned]


class TransactionPostResponse1(
    RootModel[Union[ErrorInvalidJson, ErrorUnsupportedProduct]]
):
    root: Union[ErrorInvalidJson, ErrorUnsupportedProduct]
